ktor:
  development: true
  deployment:
    port: "$PORT:8082"
  watch:
    - classes
    - resources
  application:
    modules:
      - "com.github.kondury.flashcards.placedcards.app.ApplicationJvmKt.moduleJvm"
  urls:
    - "http://127.0.0.1:8082/"
    - "http://0.0.0.0:8082/"
  #    - "http://192.168.0.182:8082/"
  logger: "logback"

placed-cards:
  repository:
    test: "$DB_TYPE_TEST:in-memory"
    prod: "$DB_TYPE_PROD:in-memory"
    psql:
      password: "$POSTGRES_PASSWORD:placedcards-pass"
      schema: "$POSTGRES_DB:placedcards"
      url: "$SQL_URL:jdbc:postgresql://localhost:5432/placedcards"
      user: "$POSTGRES_USER:postgres"

#  jwt:
#    secret: "secret"
#    issuer: "com.github.kondury"
#    audience: "flashcards-users"
#    realm: "flashcards"
#    clientId: "flashcards-service"

  jwt:
    issuer: "$JWT_ISSUER:http://localhost:9991/auth/realms/flashcards"
    audience: "$JWT_AUDIENCE:flashcards-users"
    realm: "$JWT_REALM:flashcards"
    clientId: "$JWT_CLIENT_ID:placedcards-service"
    certUrl: "$JWT_CERT_URL:http://localhost:9991/auth/realms/flashcards/protocol/openid-connect/certs"
