version: '3'

services:
  psql-cards:
    image: postgres:13.2
    container_name: psql-cards
    volumes:
      - psql_cards_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: cards-pass
      POSTGRES_USER: postgres
      POSTGRES_DB: cards
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-cards:
    image: cards-app-ktor:0.0.1
    container_name: app-cards
    ports:
      - "8081:8080"
    environment:
      LOGS_FB_HOSTS: "fluent-bit"
      LOGS_FB_PORT: 24224
      PORT: 8080
#      DB_TYPE_TEST: "in-memory"
      DB_TYPE_PROD: "psql"
      POSTGRES_PASSWORD: "cards-pass"
      POSTGRES_DB: "cards"
      POSTGRES_USER: "postgres"
      SQL_URL: "jdbc:postgresql://psql-cards:5432/cards"
      JWT_ISSUER: "http://localhost:9991/auth/realms/flashcards"
      JWT_AUDIENCE: "flashcards-users"
      JWT_REALM: "flashcards"
      JWT_CLIENT_ID: "cards-service"
      JWT_CERT_URL: "http://keycloak:8080/auth/realms/flashcards/protocol/openid-connect/certs"
    depends_on:
      psql-cards:
        condition: service_healthy

volumes:
  psql_cards_data:

