openapi: 3.0.4
info:
  title: Cards log models
  description: Log models for logging services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    LogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        requestId:
          type: string
        source:
          type: string
        card:
          $ref: '#/components/schemas/CardLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    CardLogModel:
      title: Модель лога для микросервиса cards
      type: object
      properties:
        operation:
          type: string
          enum:
            - create
            - read
            - delete
        requestCard:
          $ref: '#/components/schemas/CardLog'
        responseCard:
          $ref: '#/components/schemas/CardLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    CardLog:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        front:
          type: string
        back:
          type: string
