###
GET http://localhost:8080/

###
POST http://localhost:8080/v1/card/create
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "requestType": "createCard",
  "requestId": "create-req",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "card": {
    "front": "Front text2",
    "back": "Back text2"
  }
}

###
POST http://localhost:8080/v1/card/delete
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "requestType": "deleteCard",
  "requestId": "delete-req",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "card": {
    "id": "d0a87a1e-089d-4348-ab1e-b34633d28330",
    "lock": "dfd64b2f-070c-4230-b8d7-87e6c7b87b2b"
  }
}

###
POST http://localhost:8080/v1/card/read
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "requestType": "readCard",
  "requestId": "read-req2",
  "debug": {
    "mode": "prod",
    "stub": "success"
  },
  "card": {
    "id": "d0a87a1e-089d-4348-ab1e-b34633d28330"
  }
}